version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bloomingdales-150-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t5abbw06vwbr"
s3_prefix = "bloomingdales-150-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["BloomingdalesProductFunction=601772211076.dkr.ecr.eu-west-2.amazonaws.com/bloomingdales150-dev"]
